import './globals.css'
import type { Metadata } from 'next'
import { Fira_Sans} from 'next/font/google';
// import localFont from 'next/font/local';

const fira = Fira_Sans({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-fira',
	
});

// const grosa = localFont({
//   src: [
//     {
//       path: '../../public/fonts/Grosa/Grosa-Regular.woff2',
//       weight: '500',
//       style: 'normal',
//     },
//   ],
//   variable: '--font-grosa',
// });


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fira.className}>{children}</body>
    </html>
  )
}
